### ISSUE TITLE
check if mixpanel has been initialized or not

### ISSUE THREAD

**Issue by baldwmic** [mixpanel/mixpanel-js#133]
so the design of the library has the user call [`init`](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.init) before calling any other methods on the `mixpanel` object.

is there a way to check whether mixpanel has been initialized or not?

i'd like to only initialize the app in production environments, but i'd prefer to not manually check each time i want to call a method on the `mixpanel` object whether it has been initialized or not. does this make sense?

**Comment by tdumitrescu** [comment]
In general we want to make it obvious to users when the library is misconfigured, e.g. throwing exceptions if the instance hasn't been inited to provide a tracking token.

Would [`mixpanel.disable()`](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.disable) be sufficient for your case?

Otherwise you might be best off with a stub for your testing environments, something like
```js
if (!USE_REAL_MIXPANEL) {
  function noop() {}
  mixpanel = {
    init: noop,
    track: noop,
  };
}

mixpanel.init(/* ... */);
```

**Comment by baldwmic** [comment]
@tdumitrescu thanks for explaining the reasoning behind why errors are thrown when trying to call a method when `mixpanel.init()` hasn't been called.

it would be helpful if there was a property like `mixpanel.didInit`, a simple boolean that would return `true` if `init()` was called, `false` if not. since this library forces the consumer to call `init` successfully, the consumer has to guard against errors being thrown when calling mixpanel methods

i ended up exporting `noop` functions if the environment isn't production in a build step. but, i also had to wrap each call to `mixpanel` in a try/catch to prevent mixpanel throwing an error that crashes the app. i looked into calling `mixpanel.disable`, but it didn't prevent errors being thrown.

**Comment by nhducit** [comment]
@tdumitrescu I'm using React, when user enter `/abc` I need to send an event to track user entered to `/abc`, but the problem is the `abc` is rendered before mixpanel is load. Are there any soluton for this case?

**Comment by tdumitrescu** [comment]
You just need to make sure `mixpanel.init` has been called before `mixpanel.track` is called. There are many ways to ensure this, and it depends on how your application packages and serves JavaScript. The standard way to do this is to put the small [embed code](https://mixpanel.com/help/reference/tracking-an-event) in the `<head>` tag of your page, but you can also ensure it with synchronous module loading (e.g. importing the `mixpanel-browser` CommonJS/ES2015 module in a Webpack build and making sure `mixpanel.init` happens before bootstrapping any part of your app that needs mixpanel). If you'd like to work through the details of your particular application I suggest writing to support@mixpanel.com, they'll be happy to get it sorted out with you.

**Comment by baldwmic** [comment]
Going to close this as @tdumitrescu has explained the thinking behind the design and a solution is easy to reach by wrapping calls to the Mixpanel library

**Comment by tdumitrescu** [comment]
> @tdumitrescu I'm using React, when user enter /abc I need to send an event to track user entered to /abc, but the problem is the abc page is rendered before mixpanel is loaded. Is there any solutions for this case?

@nhducit this use case is the main point of the asynchronous loader (the standard Mixpanel installation where you install a small code snippet in your `<head>` tag). The snippet ensures that the `mixpanel` object is always available and queues up `track` calls to send once the full library has finished loading in the background.

If you want to do this with the module-bundled synchronous loader (`import mixpanel from 'mixpanel-browser';`) then you need to load your whole bundle in the head of your page, which is not recommended because it will block the whole page load while parsing and starting the entire library.

**Comment by RavenHursT** [comment]
There's nothing wrong w/ calling events on a third-party JS integration and having that code send warnings to the console or something.  But to have such integration code throw unhandled exceptions, which completely derail modern SPA apps seems irresponsible at best.

Requiring customers to write wrapping code around your code, just to ensure that it's not crashing their code is something you might want to work on.  Your code should "know" whether or not it's been initialized properly.  If not, and a method requiring initialization is called, the code should fail gracefully and possibly send warnings to the console.

But just throwing unhandled exceptions, offloads a lot of error handling responsibility off to your customers, causing frustration for your customer's engineering departments and lowering the ROI they receive from your product.

**Comment by tdumitrescu** [comment]
@RavenHursT I agree that we should provide a more straightforward/obvious way to turn the library 'off' for test modes, but "just don't call `mixpanel.init()`" is not a good solution for that. FWIW we're taking more steps right now that will make the lib load and dummy-track in server-side environments, to make it integrate more seamlessly in tests and server-side rendering flows. A config flag to pass to `mixpanel.init()` in your browser test/dev env to turn off tracking is a pretty small step beyond that, and a little more obvious than "first call `mixpanel.init()` and then call `mixpanel.disable()`".

Beyond that I think we just disagree here about API design (not that the Mixpanel SDK API was my design, but anyway...). If you've misconfigured the library (by calling tracking functions without initializing), we want the lib to fail fast with an Exception rather than throw some warnings but otherwise pretend to function. And if that happens, it will be while you're developing, not a surprise in production.

**Comment by RavenHursT** [comment]
Yeah.. we most definitely disagree (which is fine BTW.. that's how innovation and progress takes place).

Every SaaS product I've worked on, that provides a "customer-client-code-integration" SDK, has had a hard-and fast rule of not allowing exceptions in our code (even if caused by user config and utilization) to throw outside of the scope of our SDK.

The reason that is, is because you're asking your customers to trustingly inject your code into their product.  And you'l _never_ be able to know the full spectrum of use-cases that your code is going to encounter out "in the wild".  So ultimately, you can only test your code, so much, because you have no idea what all the use cases out there are.

Case in point: _My_ current use case is _not_ attempting to find a way to "turn off" mixpanel for dev envs, vs prod envs... My usecase, currently, is actually just the opposite.  I'm attempting to figure out how to ensure that every engineer that tries to run this in their local, won't be required to go and find a MP token, just so that they can go in and, say, change the label on a button.  I'm trying to actually run mixpanel and ensure that the way the MP tokens are being fed into a given env (currently via a node process env var that is then set on a config util object used throughout our app), is properly working _before_ I merge said code and deploy to shared envs.  

What's limiting here, is that there's no singular way, to tell your `mixpanel` instance "I'm not enabling you, so please don't try to do stuff, even if methods are called on you", throughout multiple import statements across multiple files.  Instead, I'm stuck w/ checking my config util, over and over and over again, to see if an MP token is set before I do anything, all over the place, w/ the MP instance in memory.. otherwise, it'll just throw an exception and crash the app.

In the end, any injected library should do it's _best_ to _not_ influence other code outside of it's scope.  Not the opposite and just assume that a consumer's development process is a certain way and that you're somehow "helping" by crashing their app, just because your instance wasn't initialized properly.  There are _much_ better ways of messaging that kind of feedback to your users, w/o making the assumptions that you've made.

**Comment by tdumitrescu** [comment]
Of course we don't want to crash easily. It's just that this is such a fundamental misconfiguration that it might as well be like calling `mixpanel.foobar()`, which one would reasonably expect to raise an exception. Note that the mixpanel lib will not throw exceptions if you initialize it with a bogus token in your test/dev env, like `mixpanel.init('TEST_TOKEN')`. Just that you can't get away with avoiding `mixpanel.init()` if you later want to call other methods on that instance.

**Comment by RavenHursT** [comment]
Awesome @tdumitrescu! That "bogus token" option is exactly what I'm looking for. I'll definitely better giving that a try! Thanks.

**Comment by zeusstl** [comment]
Recommendation for those trying to run code dependent on the mixpanel distinct_id:
```
	function method1( var1, counter ) {
		if ( typeof counter == "undefined" || counter == null )
			var counter = 0;
		try {
			var mixpanel_distinct_id = mixpanel.get_distinct_id();
			// Code that is dependent on distinct_id goes here
		} catch(e) {
			var max_attempts = 40; // How long do you want it to try before letting it fail
			counter++;
			if ( counter < max_attempts )
				setTimeout( function(){ method1(var1, counter) }, 50);
		}
	}
```
