### ISSUE TITLE
Enable compression for mixpanel js script

### ISSUE THREAD

**Issue by sashaknows** [mixpanel/mixpanel-js#168]
<img width="1117" alt="screen shot 2018-03-14 at 12 19 08" src="https://user-images.githubusercontent.com/30528582/37404443-2deea928-2792-11e8-93b1-b96bbef24487.png">

**Comment by jalamprea** [comment]
This is a big issue with the CDN.
I'm not sure why the oficial CDN of mixpanel is not using the basic optimization things like use a compression method (Gzip or Brotli) and a good expires time (greater than 1 hour, instead of just 10 minutes)
A workaround currently is to use the version on this repository:
[https://raw.githubusercontent.com/mixpanel/mixpanel-js/master/mixpanel.min.js](https://raw.githubusercontent.com/mixpanel/mixpanel-js/master/mixpanel.min.js)
Instead of the "recommended" CDN in the documentation.

Other option is (if you can compile your project with node) use the library from bower or npm and put it in your bundle with your correct optimization settings.

**Comment by reganjohnson** [comment]
Same issue. Watching for update:
![screen shot 2018-03-26 at 6 46 38 pm](https://user-images.githubusercontent.com/12020344/37937060-0c237470-3126-11e8-83b7-e41b546976c6.png)

**Comment by daviddening** [comment]
Same concern about uncompressed mixpanel.min.js

**Comment by HoangTrung** [comment]
Same here. Please fix.

**Comment by tdumitrescu** [comment]
Thanks for your patience all. We've been investigating issues with how our new CDN/storage provider handles compressed responses and have a fix ready. We're planning to reenable compression next week.

**Comment by tdumitrescu** [comment]
OK, compression has been back on since last week. I'm going to close this issue, but feel free to write in here again if there are problems.

**Comment by jalamprea** [comment]
I noticed the compression was enabled again and is working fine, but the expire header is too short. It should be at least 1 week or more, not 10 minutes.
@tdumitrescu Do you know if it will be fixed? or do you have any recommendation or workaround over the expire headers?

**Comment by tdumitrescu** [comment]
@jalamprea our policy is to use a short (10-minute) expiry whenever rolling out changes to this SDK, to facilitate quick rollbacks in case of issues. Typically we leave it in that state for a few days after a release, and then reset to the base TTL of 24 hours. If you want more fine-grained control over cache expiry on your own sites, then you'll need to host the lib yourself rather than using the auto-updating version from the Mixpanel CDN.

**Comment by josenobile** [comment]
[Google recommends](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching) minimum 1 week [There are better strategies for Invalidating and updating cached responses.](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching)

None of them work for you?

**Comment by tdumitrescu** [comment]
The full text of that recommendation is "We recommend a minimum cache time of one week and preferably up to one year _for static assets, or assets that change infrequently._" Then further: "If you need precise control over when resources are invalidated we recommend using a URL fingerprinting or versioning technique - see invalidating and updating cached responses link above."

We're happy to work on improving our caching strategies, but do realize there are a number of constraints around serving a script for 3rd-party sites; for instance, we can't use URL fingerprinting/versioning since the script reference is static on our users' sites. We now have much better ETag support in our CDN infrastructure than before and should be able to rely on that for forcing invalidation, but I can't make any promises for timeline on that work.

**Comment by sinklair** [comment]
Did this change revert? We are getting the same warning from PageSpeed.

**Comment by tdumitrescu** [comment]
Is there a particular file that's not getting compressed? I don't see any change (nor did we change any settings on our end):

$ curl -I -H "Accept-Encoding: gzip" https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js
HTTP/1.1 200 OK
X-GUploader-UploadID: AEnB2UqVIJowUpOPr112-6E09_qvzllDZJEqJfTooSHK2Hvogi6AGTV_0x_U0OW_fuJIibnggZv4DZ3jJSJLhvB6-CC-KDGoFw
Date: Mon, 24 Sep 2018 21:38:42 GMT
Expires: Mon, 24 Sep 2018 21:48:42 GMT
Last-Modified: Fri, 01 Jun 2018 21:17:23 GMT
ETag: "630a7765ef2f0246a4380df524c0604f"
x-goog-generation: 1527887843258118
x-goog-metageneration: 1
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 20918
Content-Type: application/octet-stream
**Content-Encoding: gzip**
Content-Language: en
x-goog-hash: crc32c=onCe4Q==
x-goog-hash: md5=Ywp3Ze8vAkakOA31JMBgTw==
x-goog-storage-class: MULTI_REGIONAL
Accept-Ranges: bytes
Vary: Accept-Encoding
**Content-Length: 20918**
Access-Control-Allow-Origin: *
Server: UploadServer
Age: 386
Cache-Control: public,max-age=600
Alt-Svc: clear

**Comment by sinklair** [comment]
Hmm. Perhaps we need to change something in the way we referenced on our end? Apologies of this is in error.
