### ISSUE TITLE
Support sendBeacon for exit tracking & other

### ISSUE THREAD

**Issue by rektide** [mixpanel/mixpanel-js#184]
> The challenge with tracking session length in JavaScript is programmatically defining a session-end Event. It is essentially impossible to complete a tracking API call when a user leaves your site because there is no robust handler in JavaScript for closing a browser window.

- https://help.mixpanel.com/hc/en-us/articles/115004695223-Sessions-How-To-Track

This is wrong. [`navgiator.sendBeacon()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) was added specifically to support this kind of use case. It won't detect the browser crashing or a 120-reset, but you ought to take advantage of what the platform does have, which is robust handling of window closing.

An example use:

`window.addEventListener("unload", ()=> navigator.sendBeacon(url, data));`

This could be used for exit tracking, and is also the safest, most sensible way to insure any nonsent analytics do get sent out before leaving the page.

This API was built so explicitly for the kinds of things Mixpanel does. I'm very confused why it's not used at all in the JS api and I'm dismayed at how hard your docs dodge this sensible, straightforward addition to the platform built to cover the exact use cases you say you cannot support. I would like to see Mixpanel get support for making use of sendBeacon() to insure the data gets out, even while the page is unloading.

**Comment by hiraash** [comment]
Has there been any thought/progress on this?

The above article talks about sendBeacon, but leaves it hanging there without any clue as to how the API can be used to do the session capturing.

currently is there are way we can use sendBeacon to make a ending track call? Specifically to work with time_event. I understand we can use the http API to do this, but are there any parameters needed to ensure the duration is captured?
https://mixpanel.com/help/reference/http#tracking-events

**Comment by thandaanda** [comment]
Hi Guys,
Since, Mixpanel wrote this article about session tracking way back in 2010 and there is no update regrading the same.

I have come up with quite hacky solution to send session close request and it works. Here it goes:

To Start the session:
`mixpanel.time_event('EVENT_NAME');`
This call sets timer in the cookie of Mixpanel.

I am setting an observable when :
`Observable.fromEvent(window, 'beforeunload').subscribe(() => {
      endSession();
});`
Basically, this sets the watcher for 'beforeunload' and executes 'endSession()'.


```
function endSession() {
  const userId = **USER_ID**;
  const token = **MIXPANEL_TOKEN**;
  //path to get the start time from mixpanel cookie.
  let startTime = mixpanel['persistence']['props']['__timers']['EVENT_NAME'];
  let duration = new Date().getTime() - startTime;
  duration = parseFloat((duration / 1000).toFixed(3));
  //duration is in seconds.
  let data = {
    event: 'EVENT_NAME',
    properties: {
      token: token,
      distinct_id: userId,
      $duration: duration,
      //optional properties to send
      ...mixpanel._.info.properties(),
      ...mixpanel['persistence'].properties()
    }
  };
  let newdata = btoa(JSON.stringify(data));
  navigator.sendBeacon('https://api.mixpanel.com/track/?data=' + newdata);
}
```

Make sure to replace **EVENT_NAME** with your desired event name.

**Comment by albertstill** [comment]
I reached out to Mixpanel directly in Aug 19' and they told me they had no immediate plans to support it due to resource limitations. Years ago [`sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) was added to the Web API for tracking reasons, to help devs and tracking companies like Mixpanel when tracking events before a page will unload. So I find it really surprising any serious tracking company would not offer `sendBeacon` in their API, especially that it's not very difficult to add it. Google [supports](https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms) it and will make it default soon.

Does Mixpanel have any update on this, or insight into why they don't support it? It would be great if it was part of the MP JS SDK. I really don't want to have to write a custom sendBeacon [HTTP](https://developer.mixpanel.com/docs/http) request solution and have to think about super properties etc. Nor do I want to have to use the `mixpanel.track` callback arg which will hinder UX as the user waits for the MP network request and create callback soup in our code.

Cheers

**Comment by tdumitrescu** [comment]
It's mainly a matter of priorities; there hasn't been enough demand to bring it to the top of the backlog yet. We have some updates in the works at the moment that solve similar problems in a different way, e.g., persisting events in browser storage until they're acknowledged as tracked by the HTTP API (letting later pageloads flush anything which may not have made it through previously). This approach works to minimize data loss in the case of network unavailability, but doesn't work with `sendBeacon` since there's no way to know whether a sendBeacon request succeeded.

Likely we'll offer some configuration options to allow users to enable sendBeacon tracking optionally, but it won't become the default due to its fire-and-forget nature, as we're working towards more robust retry mechanisms.

It may also be feasible to support one-off sendBeacon usage if you want to use it just for page-unload scenarios, something like:
```js
window.addEventListener(`unload`, function() {
  mixpanel.track(`My event`, myProps, {transport: `sendBeacon`});
});
```
If something like the above usage would be good enough for your current needs, we can get that implemented in the near term.

**Comment by albertstill** [comment]
Thanks for the quick response @tdumitrescu. Interesting point about data loss and sendBeacon.

We'd really appreciate the `{transport: 'sendBeacon'}` option here at Domain, happy to test it if you want to beta release it.

Cheers

**Comment by tdumitrescu** [comment]
@albertstill FYI I put an implementation up at https://github.com/mixpanel/mixpanel-js/pull/240

**Comment by harry-wood** [comment]
So that was added in Jan 2020. Is there some documentation with an example snippet to make use of this? I found the snippet you gave above didn't work. "beforeunload" instead of "unload" worked better, but probably better is "visibilitychange", as per [the snippet I give in this answer](https://stackoverflow.com/a/68492307/338265) (My attempt at providing the missing documentation)

**Comment by tdumitrescu** [comment]
We don't have documentation available of page-exit strategies, as that's not really part of the SDK (except for the built-in case when queue/batch/retry mode is on, which doesn't involve any extra code for the developer). Basically if you track with `{transport: 'sendBeacon'}` that will use the `navigator.sendBeacon` API instead of XHR, and that's about the extent of the tracking changes.

That being said, in terms of how you would implement, yes `visibilitychange` is supposed to be the most reliable event, but it comes with a caveat, in that it will fire every time the user switches away from the tab (or back to the tab). By inspecting `document.visibilityState` you can see whether the user is clicking to or away from the tab/page, but AFAIK there is no reliable way to tell that the user "closed" the page since beforeunload/unload are sketchy.

**Comment by Kvisaz** [comment]
Hi, everyone

You must know - "unload" event is totally unstable and unreliable with sendBecon

just read this - https://github.com/mdn/content/issues/2692

All these years we all used sendBeacon in totally wrong way
