### ISSUE TITLE
Mixpanel set too many duplicated cookies

### ISSUE THREAD

**Issue by lawulu** [mixpanel/mixpanel-js#207]
UserAgent: 
Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_1 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A402      MicroMessenger/7.0.3(0x17000321) NetType/WIFI Language/zh_CN
(This is a very popular inner-browser used by Tencent Wechat in China)

Any suggestion to solve this issue?

![image](https://user-images.githubusercontent.com/5326606/51900560-962a7980-23f0-11e9-8493-05aef6643f23.png)

**Comment by tdumitrescu** [comment]
The cookie name format is `mp_<token>_mixpanel`, so each of those represents a library instance that you instantiated with a different token or project. This looks like a Mixpanel integration issue on your site rather than a library issue, so we're going to close this. You can get integration help at https://community.mixpanel.com/ or via our support agents. Feel free to respond/reopen if there's a reason to believe this is actually a library bug.
