### ISSUE TITLE
New Cookie Policy for Chrome: SameSite attribute

### ISSUE THREAD

**Issue by james-criscuolo** [mixpanel/mixpanel-js#224]
Since (I believe) the release of Chrome 77, logging into my app (which initializes `mixpanel-js`) shows this warning:
```
A cookie associated with a cross-site resource at http://mixpanel.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```
I believe this is internal to the library.

**Comment by jpduckwo** [comment]
Please update mixpanel-browser to set the SameSite=None flag for the cookies

**Comment by tdumitrescu** [comment]
The cookies used by this library for tracking are same-site by default: they will be set on your (sub)domains, not mixpanel.com. Without looking at dev info, I'd suspect that what you're seeing is the result of your own mixpanel.com cookie being sent along with the lib's tracking requests to api.mixpanel.com, i.e. you're seeing this because you're a mixpanel.com user, but your users won't see it and it won't affect your app's own tracking. If you're seeing your app's tracking props ending up in a cookie on the mixpanel.com domain, please let us know here so we can investigate.

**Comment by jpduckwo** [comment]
@tdumitrescu thanks, I think you're correct. Just tested in an incognito window and didn't get the message for mixpanel.

**Comment by james-criscuolo** [comment]
Sorry for the late response, but I was also able to confirm that via an incognito window. Thanks, I'll close this one.
