### ISSUE TITLE
Mixpanel blocked by uBlock despite using api_host

### ISSUE THREAD

**Issue by mir3z** [mixpanel/mixpanel-js#274]
We are using Mixpanel with `api_host` specified to proxy its traffic through our backend. For a long time it was enough to cheat adblockers and have Mixpanel integration up&running.
Recently we noticed that Mixpanel calls are blocked regardless of the above by uBlock Origin because of `/track/?data=` phrase on the EasyPrivacy list.

The solution for the above would be to provide more configurability in `init` method to override `/track` endpoint URL to something else, for instance `/definitely-not-tracking`. Then on the proxy level the `/definitely-not-tracking` URL would redirect to yours original `/track` endpoint.

**Comment by tdumitrescu** [comment]
That's a good idea. As proxy servers get more popular we'll want more configurability around them.

In the meanwhile, you should be able to avoid that URL match by sending your tracking requests over POST rather than GET with URL params (which also has other advantages). POST has been the default in the SDK for about a year since [v2.32.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.32.0).

You can enable tracking over POST either with the `api_method` config param, or if you're updating to a more recent version of the SDK, the recommended config is to use `{batch_requests: true}` which will go over POST in addition to offering support for queueing/batching requests and automatically retrying in case of network failures.
