### ISSUE TITLE
Track does not support js native Error 

### ISSUE THREAD

**Issue by Amirault** [mixpanel/mixpanel-js#317]
Track does not support js native Error 

When using mixpanel with : `mixpanel.track(event, { err: new Error });` 

it makes mixpanel crash with :
<img width="713" alt="Screenshot 2021-12-13 at 16 26 41" src="https://user-images.githubusercontent.com/8234509/145839814-b18b4d6e-3171-4f90-9a5f-23ea0f67679d.png">

My solution: avoiding using instances of Error directly and make a serialization before the usage 

something like :
```
const myErr = err instanceof Error
    ? JSON.stringify(err, Object.getOwnPropertyNames(err))
    : err
mixpanel.track(event, { err: myErr })
```

Is it possible to provide a fix for this one?

**Comment by tdumitrescu** [comment]
Thanks @Amirault. Sorry about the inscrutable error. That generally happens when you pass an Object to `track()` that has a circular reference to itself somewhere. You want to provide property values that are either simply serializable, or preferably already serialized exactly how you want them. Your last code block does this already, by providing a String as the value instead of the raw Error object. For complex native types like Error, individual devs/projects will probably want to decide what exactly they want to track about them; for instance by stringifying all "own properties" of the Error you'll get very different results in Firefox vs Chrome, which may be fine or not for your own use case (vs alternative approaches like tracking simply `{'error message': err.message}`). Hope this helps!
