### ISSUE TITLE
Mixpanel instance is not defined during mixpanel.init loaded event

### ISSUE THREAD

**Issue by shawn-simon** [mixpanel/mixpanel-js#47]
See example here:

http://codepen.io/anon/pen/vOMPVM

As you can see here: https://github.com/mixpanel/mixpanel-js/blob/master/mixpanel.js#L4718 The instance is not set on the window until after the loaded event. Reported this already but posting it here, seems kinda serious.

**Comment by tdumitrescu** [comment]
Hi, thanks for the report and code sample. It looks like the documentation is a bit out of date here. The `loaded` callback is passed the specific `mixpanel` lib object as a parameter, which you should use to access it rather than the global (also useful if you're juggling multiple implementations on a single page). An example from the test suite: https://github.com/mixpanel/mixpanel-js/blob/b944e9d193e4fe07417d02fb2fc2f1920a30189a/tests/tests.html#L29-L31

I'll leave this issue open until we get the documentation updated.

**Comment by shawn-simon** [comment]
Where is the documentation?

**Comment by hoodwink73** [comment]
This also then needs to be changed. https://mixpanel.com/help/questions/articles/how-to-prevent-getdistinctid-and-getproperty-from-returning-undefined

**Comment by tdumitrescu** [comment]
Thanks for the heads up!

**Comment by artdent** [comment]
This sharp edge on the API broke my page in a manner that took forever to diagnose, for two reasons:
- The breakage only happened some of the time, depending on how long it took the mixpanel external js to load. (For that reason, adding a breakpoint made the problem go away.)
- The error that would have caught this -- "You must name your new library: init(token, config, name)" -- is only printed if you pass the undocumented {debug: true} flag in the mixpanel config.

It would be very very helpful if the documentation called out the fact that the init function on the mixpanel stub and the init function on the full mixpanel object are in fact two completely different functions that just happen to have the same name, and that's why it's bad to call mixpanel.init late. It also would be nice if the usage error were always printed and not hidden behind a debug flag.

**Comment by tdumitrescu** [comment]
Documentation has been updated at https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.get_distinct_id and https://mixpanel.com/help/questions/articles/how-to-prevent-getdistinctid-and-getproperty-from-returning-undefined. Thanks all.

**Comment by davnicwil** [comment]
I just tripped over this issue today.

I'm new to mixpanel and this is definitely still not made obvious at all in the docs.

For instance, here are the docs for `mixpanel.init`: https://mixpanel.com/help/reference/javascript-full-api-reference

They point to this 'example config' which shows a loaded fn without a `mixpanel` arg: https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b0e066482836e2c5484558e3c356d492a/src/mixpanel-core.js#L95

This is pretty unintuitive, and I don't understand why this has to be the case - presumably the line `callback(mixpanel)` exists somewhere -- why not just add `window.mixpanel = mixpanel` before that line? 

Genuine question, I am sure there is a good reason why this isn't done :-)
