### ISSUE TITLE
No way to set "HttpOnly" on MixPanel cookie.

### ISSUE THREAD

**Issue by TimeBomb** [mixpanel/mixpanel-js#74]
We have a security requirement to mark the Mixpanel cookie as both `secure` and `HttpOnly`.
We can set `secure_cookie` in `mixpanel.set_config` to add `secure` to the cookie, but there is no option to add `HttpOnly` to the cookie. An option for this would be appreciated. Thanks.

Information on HttpOnly cookies: https://www.owasp.org/index.php/HttpOnly

**Comment by tdumitrescu** [comment]
I'm not sure how `HttpOnly` would work with the mixpanel lib - it reads values out of the cookie at several spots, most importantly to set superproperties. FWIW there's no session token or auth data of any kind stored in the cookie, just property definitions and various data queue metadata. And if you're only worried about protecting data which might go over a network in request headers, you can use config option `persistence: 'localStorage'` to use localStorage instead of cookies.

**Comment by TimeBomb** [comment]
Looks like you're right, I implemented Http Only in a similar fashion to the secure_cookie options, and it seems to have worked as I expected, but there were persistence-related issues when I enabled it. They went away and mixpanel worked again when I stopped using HttpOnly. I'll look into using local storage instead, thanks.

**Comment by tdumitrescu** [comment]
Sounds good! If you need any help don't hesitate to write in to support@mixpanel.com.
