### ISSUE TITLE
JS library does not support buffering / batch events track

### ISSUE THREAD

**Issue by fproulx-pbox** [mixpanel/mixpanel-js#84]
The iOS and Android Mixpanel clients support buffer and send events as batch.

I hate to see dozens of events that occur at the same second flood the network....

**Comment by tdumitrescu** [comment]
Indeed, there's no built-in batching currently. Pull requests are welcome as long as they maintain backwards compatibility. If you want to look for a workaround for your specific situation, drop a line at support@mixpanel.com and we'll get you set up!

**Comment by piyushcsiitd** [comment]
Can someone is review/approve if i were to submit fix for this?
Thanks vm.

**Comment by tommysanterre** [comment]
I see multiple reference to batch requests in the code https://github.com/mixpanel/mixpanel-js/search?q=batch_requests
But the option does not seem to work. Is this still not supported?

**Comment by tommysanterre** [comment]
Nevermind it works!
I think this issue should be closed.

**Comment by tdumitrescu** [comment]
Thanks for resurfacing this issue @tommysanterre. Batching has been publicly available since [v2.36.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.36.0). We're gradually making this the default mode (currently true for 60% of projects) but you can always turn it on explicitly with the configuration flag `{batch_requests: true}`.
