### ISSUE TITLE
Mixpanel javascript blob default value assigned

### ISSUE THREAD

**Issue by roderickhsiao** [mixpanel/mixpanel-js#96]
Hi team

https://mixpanel.com/help/reference/tracking-an-event

currently the js blob will assign an array to the global `mixpanel` variable if the javascript cannot be fetch, wondering why we are assigning array instead of object (or even better, we can leave unassigned)

the reason is we are having defensive code against `mixpanel` when execute any commend using just check `if (mixpanel)`, but as it is currently assigned an array, we are getting javascript error.

Thanks

**Comment by tdumitrescu** [comment]
This is part of the asynchronous loading mechanism. The point is that after sticking a small amount of JS code into your page's `<head>` tag (https://github.com/mixpanel/mixpanel-js/blob/master/mixpanel-jslib-snippet.min.js), you can call mixpanel methods like `mixpanel.track()` and the updates will be queued up to be executed once the complete library has finished loading from the network, without blocking your page load. You should never have to write `if (mixpanel)`.

**Comment by roderickhsiao** [comment]
thanks @tdumitrescu 

we are having code using api like mixpanel.get_property which will not be there if the js is not loaded. 

We would like to make sure our code is defensive enough that if external partner javascript fails, any suggestions?

**Comment by roderickhsiao** [comment]
or we should add the function in the shallow copy 
https://github.com/mixpanel/mixpanel-js/blob/master/mixpanel-jslib-snippet.js#L75

**Comment by tdumitrescu** [comment]
The typical solution for mixpanel-dependent code like that is to launch it from the library's `loaded` callback, e.g.:
```javascript
// read distinct_id value after the mixpanel library has loaded
var distinct_id;
mixpanel.init('YOUR PROJECT TOKEN', {
    loaded: function() {
        distinct_id = mixpanel.get_distinct_id();
    }
});
```
We don't add methods like `get_distinct_id` or `get_property` to the embed code because:
- they can't return anything meaningful before the library has loaded
- their names increase the length of the embedded snippet (and as strings can't be minified), meaning the snippet blocks the page load for longer

Note that it's also possible to install the lib for entirely synchronous self-hosted loading with Webpack, Browserify, or other CommonJS packagers; there's also an AMD build (require.js), which will solve the problem similarly but asynchronously.

**Comment by roderickhsiao** [comment]
Oh thanks! it looks clear, we are trying not to bundle with our regular js so that the instrumentation can run earlier before other javascript kick in.

Btw the async queue for track event is smart :)

**Comment by tdumitrescu** [comment]
Cool, glad to help. Feel free to open any code-related issues on this repo, or if you need implementation and usage advice, support@mixpanel.com is always very helpful.
