### ISSUE TITLE
Question about user identify 

### ISSUE THREAD

**Issue by roderickhsiao** [mixpanel/mixpanel-js#99]
Hi team,

a question about the js api call regarding to user identity.

So we are using `mixpanel.alias` when user signup and `mixpanel.identify` for user login.

For some reason we have some incorrect unique id set to some user, (seeing from mixpanel live view dashbroad)

so we try to have fix the issue by adding the below code when our app starts. 

```
const id = mixpanel.get_distinct_id();
if (INCORRECT_FORMAT) {
   mixpanel.people.set({
      '$email': `${CORRECT_EMAIL}`,
      '$name': ${CORRECT_NAME}`
  });
  mixpanel.identify(`${CORRECT_ID}`);
}
```

However, it doesnt seems to showing correct beacon on the live view (checking from browser console also mixpanel debug plugin that we are sending correct `distinct_id`.

Any suggestion?

**Comment by tdumitrescu** [comment]
This sounds like an implementation issue which our support team can help with. They've got a lot of experience helping correct id and aliasing issues, and can work with you personally to get your project straightened out. Just drop that text in an email to support@mixpanel.com. I'm going to close this issue out for now, but if it turns out to be a lib code issue that our engineering team can help with, will be happy to reopen.

**Comment by roderickhsiao** [comment]
thanks
